### ISSUE TITLE
Modifier to add whitespace between example components

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#841]
Rendering multiple variations of the same component (like a button) on a single line is a very common use case. Right now you have to add some custom styles to add whitespace between components, or use spaces — both solutions aren’t perfect.

Add a new modifier (like `static` or `noeditor`), `spaced` (?) that will add styles like:

```css
// Almost pseudocode
.example > *:not(:last-child) {
  margin-right: 8px;
}
```
