### ISSUE TITLE
Isolate components with `position: fixed`

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#930]
Currently, elements with `position: fixed` will be positioned relative to the `body` element which holds the styleguide. But ideally those elements should remain inside example's wrapper elements. 

Example:

![2018-04-07 at 10 12](https://user-images.githubusercontent.com/11071/38452837-313c92b2-3a4c-11e8-9f26-0571cd5ddea3.png)

You can see an example of faulty positioned element live at https://react.feedly.com

This post summarizes on how easy it is to fix it: https://medium.com/@didoo/keep-it-simple-stupid-b5fe06b1b025

Apparently, all we need to do is to add a CSS `transform` to the wrapper element: 

```css
.styleguide-frame {
  position: relative;
  transform: translate3d(0, 0, 0); /* <-- THIS LINE MAKES THE TRICK! */
  outline: 1px solid #eaeaea;
}
```

Source: https://gist.github.com/didoo/873bf9eb23669f8ac4d468c580d5cdfd#file-styleguide-frame-css
